### ISSUE TITLE
Which font is used in the screenshot? 

### ISSUE THREAD

**Issue by torarnv** [fnogatz/cli-cal#1]
The spacing between the boxes look really nice, I can't reproduce it with my current terminal font. Thanks!

<img src="https://github.com/fnogatz/cli-cal/raw/master/screenshot.png">

**Comment by fnogatz** [comment]
It's simply [Ubuntu Mono derivative Powerline](https://github.com/powerline/fonts/blob/master/UbuntuMono/Ubuntu%20Mono%20derivative%20Powerline.ttf).

**Comment by torarnv** [comment]
Strange, this is how it looks in iTerm2 on macOS:

https://www.dropbox.com/s/121lwhicnlnthja/Screenshot%202017-05-22%2017.53.05.png?dl=0

with that font

**Comment by fnogatz** [comment]
Closing this here :)
